# -*- coding: utf-8 -*-
"""project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UiK1aj9R7c79PAPw0BrAhdf4Qdw7s9h3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

df = pd.read_csv("/content/test.csv", encoding='latin1')

df.head()

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns)

print(df.isnull().sum())

df = df.dropna()

df = df.drop_duplicates()

print(df["Sentiment"].value_counts())

plt.figure(figsize=(7, 5))

sns.countplot(
    data=df,
    x="sentiment"
)

plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")

plt.show()

def clean_text(text):

    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove punctuation
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_Review"] = df["text"].apply(clean_text)

df[["Text", "clean_Review"]].head()

X = df["Text"]
y = df["Sentiment"]

print(X.head())
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

print("Training shape:", X_train_tfidf.shape)
print("Testing shape:", X_test_tfidf.shape)

lr_model = LogisticRegression(
    max_iter=1000
)

lr_model.fit(
    X_train_tfidf,
    y_train
)

lr_predictions = lr_model.predict(X_test_tfidf)

lr_accuracy = accuracy_score(
    y_test,
    lr_predictions
)

print("Logistic Regression Accuracy:",
      lr_accuracy)

print(
    classification_report(
        y_test,
        lr_predictions
    )
)

nb_model = MultinomialNB()

nb_model.fit(
    X_train_tfidf,
    y_train
)

nb_predictions = nb_model.predict(
    X_test_tfidf
)

nb_accuracy = accuracy_score(
    y_test,
    nb_predictions
)

print(
    "Naive Bayes Accuracy:",
    nb_accuracy
)

print(
    classification_report(
        y_test,
        nb_predictions
    )
)

svm_model = LinearSVC()

svm_model.fit(
    X_train_tfidf,
    y_train
)

svm_predictions = svm_model.predict(
    X_test_tfidf
)

svm_accuracy = accuracy_score(
    y_test,
    svm_predictions
)

print(
    "SVM Accuracy:",
    svm_accuracy
)

print(
    classification_report(
        y_test,
        svm_predictions
    )
)

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Naive Bayes",
        "SVM",
        "XGBoost Classifier" # Added XGBoost Classifier
    ],

    "Accuracy": [
        lr_accuracy,
        nb_accuracy,
        svm_accuracy,
        xg_accuracy # Added XGBoost accuracy
    ]
})

results

plt.figure(figsize=(8, 5))

sns.barplot(
    data=results,
    x="Model",
    y="Accuracy"
)

plt.ylim(0, 1)

plt.title("Model Accuracy Comparison")

plt.show()

models = {
    "Logistic Regression": lr_model,
    "Naive Bayes": nb_model,
    "SVM": svm_model,
    "XGBoost Classifier": xg_final # Added XGBoost model
}

accuracies = {
    "Logistic Regression": lr_accuracy,
    "Naive Bayes": nb_accuracy,
    "SVM": svm_accuracy,
    "XGBoost Classifier": xg_accuracy # Added XGBoost accuracy
}

best_model_name = max(
    accuracies,
    key=accuracies.get
)

best_model = models[best_model_name]

print("Best Model:", best_model_name)
print("Best Accuracy:", accuracies[best_model_name])

best_predictions = best_model.predict(
    X_test_tfidf
)

cm = confusion_matrix(
    y_test,
    best_predictions
)

plt.figure(figsize=(10, 5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=best_model.classes_,
    yticklabels=best_model.classes_
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

print(
    classification_report(
        y_test,
        best_predictions
    )
)

def predict_sentiment(review):

    cleaned = clean_text(review)

    vectorized = vectorizer.transform(
        [cleaned]
    )

    prediction = best_model.predict(
        vectorized
    )[0]

    return prediction

review = "I absolutely love this product!"

print(
    predict_sentiment(review)
)

review = "This product is terrible and I hate it."

print(
    predict_sentiment(review)
)

review = "The product arrived yesterday."

print(
    predict_sentiment(review)
)

def predict_with_confidence(review):

    cleaned = clean_text(review)

    vectorized = vectorizer.transform(
        [cleaned]
    )

    prediction = best_model.predict(
        vectorized
    )[0]

    if hasattr(best_model, "predict_proba"):

        probabilities = best_model.predict_proba(
            vectorized
        )[0]

        confidence = max(probabilities) * 100

        return prediction, confidence

    return prediction, None

from xgboost import XGBClassifier
import numpy as np # Import numpy for np.unique

# Instantiate XGBClassifier for classification task
xg = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42,
    # Assuming y_train_encoded is already prepared and in scope
    num_class=len(np.unique(y_train_encoded))
)

# Fit the model using the preprocessed TF-IDF features and encoded labels
# Assuming X_train_tfidf and y_train_encoded are available from previous cells
xg_final = xg.fit(X_train_tfidf, y_train_encoded)

# Make predictions on the test set with the trained XGBoost model
xg_predictions = xg_final.predict(X_test_tfidf)

# Calculate accuracy
xg_accuracy = accuracy_score(y_test_encoded, xg_predictions)
print(f"XGBoost Classifier Accuracy: {xg_accuracy:.4f}")

# Display classification report
print("\nXGBoost Classifier Classification Report:")
print(classification_report(y_test_encoded, xg_predictions, target_names=label_encoder.classes_))

import joblib

joblib.dump(xg_final,'sentiment analysis')

model = joblib.load('sentiment analysis')

df.head(1)

import pandas as pd
data_new = pd.DataFrame({
   'text':['I love this product!'],
   'sentiment':['positive']
},index=[0])

review_new = data_new['text'].iloc[0]
predicted_sentiment, confidence = predict_with_confidence(review_new)

print(f"New Review: '{review_new}'")
print(f"Predicted Sentiment: {predicted_sentiment}")
if confidence is not None:
    print(f"Confidence: {confidence:.2f}%")

# Overall summary of the notebook execution
print("\n--- Notebook Summary ---")
print("Data loaded and cleaned.")
print("TF-IDF vectorization applied.")
print("Multiple classification models trained and evaluated (Logistic Regression, Naive Bayes, SVM, XGBoost).")
print("Best performing model identified as SVM with an accuracy of 0.6308.")
print("Demonstrated sentiment prediction on new review text.")
print("The XGBoost model (xg_final) was also saved using joblib.")

joblib.dump(best_model, 'svm_model.joblib')

joblib.dump(best_model, 'svm_model_corrected.joblib')

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer # Added import

# Ensure X and y are defined from the dataframe
X = df["text"]
y = df["sentiment"]

# Ensure X_train, X_test, y_train, y_test are defined
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# Encode target labels
label_encoder = LabelEncoder()
# Fit the encoder on all unique labels present in both training and testing sets
label_encoder.fit(pd.concat([y_train, y_test]))

y_train_encoded = label_encoder.transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Define and fit TfidfVectorizer to create X_train_tfidf and X_test_tfidf
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)
X_train_tfidf = vectorizer.fit_transform(X_train) # Defined X_train_tfidf here
X_test_tfidf = vectorizer.transform(X_test) # Also define X_test_tfidf for consistency if needed later

model = XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42,
    num_class=len(label_encoder.classes_)
)

model.fit(X_train_tfidf, y_train_encoded)

xg_final.save_model('xgb_model.json')





